[build]
  command = "echo 'Environment check:' && env | grep -E 'NEXT|MONGO|AUTH' && npm run build"
  publish = ".next"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "false"
  NODE_VERSION = "18"
  NEXT_USE_NETLIFY_EDGE = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# More specific redirects for NextAuth API routes
[[redirects]]
  from = "/api/auth/*"
  to = "/.netlify/functions/next_api_auth_:splat"
  status = 200
  force = true

# Default redirect for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# Add headers for CORS
[[headers]]
  for = "/api/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept"
