[build]
  command = "echo 'Environment check:' && env | grep -E 'NEXT|MONGO|AUTH' && npm run build"
  publish = ".next"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "false"
  NODE_VERSION = "18"
  NEXT_USE_NETLIFY_EDGE = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Change the redirect patterns for auth routes to be more specific and give them higher priority
[[redirects]]
  from = "/api/auth/session"
  to = "/.netlify/functions/next_api_auth_session"
  status = 200
  force = true

[[redirects]]
  from = "/api/auth/signin/*"
  to = "/.netlify/functions/next_api_auth_signin_:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/auth/callback/*"
  to = "/.netlify/functions/next_api_auth_callback_:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/auth/*"
  to = "/.netlify/functions/next_api_auth_:splat"
  status = 200
  force = true

# Additional redirect to handle public files
[[redirects]]
  from = "/favicon.ico"
  to = "/favicon.ico"
  status = 200
  force = true

# Default redirect for client-side routing (lower priority than API routes)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# Add headers for CORS
[[headers]]
  for = "/api/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept"
