[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_PUBLIC_API_URL = "https://uorganizer.netlify.app"
  NEXTAUTH_URL = "https://uorganizer.netlify.app"
  NODE_VERSION = "18"
  
[functions]
  # Increase API function timeout and memory
  node_bundler = "esbuild"
  external_node_modules = ["bcryptjs", "mongodb"]
  included_files = ["lib/**", "models/**"]

# Make API routes work correctly
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

# All other routes go to Next.js
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/next"
  status = 200
