[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[functions]
  included_files = ["public/*", "!node_modules/next/dist/compiled/webpack/bundle5.js"]
