[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_NETLIFY_IDENTITY_ENABLED = "true"
  NEXT_PUBLIC_NETLIFY_URL = "https://uorganizer.netlify.app"
  NEXT_PUBLIC_NEXTAUTH_URL = "https://uorganizer.netlify.app"
  NEXTAUTH_URL = "https://uorganizer.netlify.app"
  NODE_ENV = "production"

# Identity settings
[dev]
  command = "npm run dev"
  functions = ".netlify/functions"
  publish = ".next"
  autoLaunch = true

# Handle redirects for client-side routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Enable Netlify Identity
[template.environment]
  NETLIFY_IDENTITY_ENABLED = "true"
