[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_PUBLIC_API_URL = "https://uorganizer.netlify.app"
  NEXTAUTH_URL = "https://uorganizer.netlify.app"
  NODE_VERSION = "18"
  
[functions]
  # Increase API function timeout and memory
  node_bundler = "esbuild"
  external_node_modules = ["bcryptjs", "mongodb"]
  included_files = ["lib/**", "models/**"]

# Remove the redirects that might be causing conflicts with Next.js API routes
# Let the Next.js plugin handle the routing properly
