[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Keep environment variables
[build.environment]
  NEXT_PUBLIC_API_URL = "https://uorganizer.netlify.app"
  NEXTAUTH_URL = "https://uorganizer.netlify.app"
  NEXTAUTH_SECRET = "57dd7df0034aacd3fec020a220930081d9d3e9318b54c082b55cad978f57c064"
  NODE_VERSION = "18"
  DEBUG = "true"
  
[functions]
  # Increase function timeout to 30 seconds (default is 10)
  timeout = 30
  node_bundler = "esbuild"
  external_node_modules = ["bcryptjs", "mongodb", "jsonwebtoken", "cookie"]
  included_files = ["lib/**", "models/**"]
  
# Function-specific settings
[functions.api_custom-login]
  # Give more resources to the login function
  memory = 1024
  timeout = 30

# Add function log settings
[functions.next_auth]
  included_files = ["public/**", ".env", ".env.*"]

# Add headers for security and CORS
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Access-Control-Allow-Origin = "*"
