[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Keep environment variables
[build.environment]
  NEXT_PUBLIC_API_URL = "https://uorganizer.netlify.app"
  NEXTAUTH_URL = "https://uorganizer.netlify.app"
  NEXTAUTH_SECRET = "57dd7df0034aacd3fec020a220930081d9d3e9318b54c082b55cad978f57c064"
  NODE_VERSION = "18"
  DEBUG = "true"
  
[functions]
  # Increase API function processing resources
  node_bundler = "esbuild"
  external_node_modules = ["bcryptjs", "mongodb", "jsonwebtoken", "cookie"]
  included_files = ["lib/**", "models/**"]

# Function-specific settings
[[functions]]
  # Target the login function specifically
  pattern = "api/custom-login"
  included_files = ["lib/**", "models/**"]
  memory_size = 1024
  timeout_seconds = 30

# For NextAuth functions
[[functions]]
  pattern = "api/auth/*"
  included_files = ["public/**", ".env", ".env.*"]
  timeout_seconds = 30

# Add headers for security and CORS
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Access-Control-Allow-Origin = "*"
